NapariliDB/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

NapariliDV/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from .sitemaps import (
    HomeViewSitemap,
    StaticViewSitemap, 
    OtherStatisViewSitemap,
    ProjectViewSitemap, 
    BlogViewSitemap,
)

from home.views import handler404


sitemaps = {
    'home': HomeViewSitemap,
    'static': StaticViewSitemap,
    'other_static': OtherStatisViewSitemap,
    'projects': ProjectViewSitemap,
    'blog': BlogViewSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls', namespace='home')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contacts/', include('contacts.urls', namespace='contacts')),

    path('not-found/', handler404, name='not-found'),

    re_path(r'^robots\.txt$', serve, {
        'document_root': settings.BASE_DIR,
        'path': 'robots.txt',
    }),
    
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
)
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.handler404'

blog/urls.py
from django.urls import path
from .views import *


app_name = 'blog'


urlpatterns = [
    path('', BlogView.as_view(), name='blog'), 
    path('article/<slug:article_slug>', ArticleView.as_view(), name='article'), 
]

contacts/urls.py
from django.urls import path
from .views import *


app_name = 'contacts'


urlpatterns = [
    path('', ContactsView.as_view(), name='contacts'), 
    path('gallery/', GalleryView.as_view(), name='gallery'), 
    path('about/', AboutCompanyView.as_view(), name='about_company'),
    path('privacy_policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),

    path('api/save-request/', SaveRequestView.as_view(), name='save_request'),
    path('api/gallery-fiilters/', GalleryPhotosAPIView.as_view(), name='gallery_filters'),
    path('api/gallery-details/<int:project_id>/', GalleryDetailsAPIView.as_view(), name='gallery_details'),
]

home/urls.py
from django.urls import path
from .views import *


app_name = 'home'


urlpatterns = [
    path('', HomeView.as_view(), name='home'), 

    path('api/best-projects-filter/', BestProjectsFilterAPIView.as_view(), name='best_projects_filter'),
]

contacts/models.py
from django.db import models
from home.services import convert_image_to_webp


class Worker(models.Model): 
    name = models.CharField('Имя', max_length=100)
    role = models.TextField('Роль')
    photo = models.ImageField('Фото', upload_to='contacts/workers')

    class Meta: 
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def __str__(self): 
        return f'{self.name}, {self.role}'
    
    def save(self, *args, **kwargs):
        if self.pk:
            old_image = self.__class__.objects.filter(pk=self.pk).first().photo
            if old_image and self.photo and old_image.name == self.photo.name:
                super(self.__class__, self).save(*args, **kwargs)
                return
            
        webp_image = convert_image_to_webp(self.photo)
        if webp_image:
            self.photo.save(webp_image.name, webp_image, save=False)
        
        super(self.__class__, self).save(*args, **kwargs)


class PrivacyPolicy(models.Model): 
    class Meta: 
        verbose_name = 'Политика конфиденциальности'
        verbose_name_plural = 'Политика конфиденциальности'

    def save(self, *args, **kwargs):
        if self.__class__.objects.count():
            self.pk = self.__class__.objects.first().pk
        super().save(*args, **kwargs)

    @classmethod
    def get_instance(cls) -> "PrivacyPolicy":
        instance, created = cls.objects.get_or_create(id=1)
        return instance
    
    def __str__(self) -> str: 
        return 'Политика конфиденциальности'


class PrivacyPolicyParagraph(models.Model): 
    title = models.TextField('Заголовок') 
    content = models.TextField('Содержание')
    privacy_policy = models.ForeignKey(verbose_name='Политика конфиденциальности', to=PrivacyPolicy, on_delete=models.CASCADE, related_name='paragraphs')


class Request(models.Model): 
    name = models.CharField('Имя', max_length=25)
    phone = models.CharField('Телефон', max_length=18)
    message = models.TextField('Сообщение', max_length=200, null=True, blank=True)
    created_at = models.DateTimeField('Дата и время создания', auto_now_add=True)
    is_closed = models.BooleanField('Обработано', default=False)

    class Meta: 
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'
    
    def __str__(self) -> str: 
        return f'{"Обработано" if self.is_closed else "Не обработано"}, {self.created_at}, {self.phone}'
    

class CertificatePhoto(models.Model): 
    photo = models.ImageField('Фото', upload_to='contacts/certificates') 

    class Meta: 
        verbose_name = 'Фото сертификата'
        verbose_name_plural = 'Сертификаты'

    def save(self, *args, **kwargs):
        if self.pk:
            old_image = self.__class__.objects.filter(pk=self.pk).first().photo
            if old_image and self.photo and old_image.name == self.photo.name:
                super(self.__class__, self).save(*args, **kwargs)
                return
            
        webp_image = convert_image_to_webp(self.photo)
        if webp_image:
            self.photo.save(webp_image.name, webp_image, save=False)
        
        super(self.__class__, self).save(*args, **kwargs)

    def __str__(self):
        return f'Сертификат {self.pk}'
    

class Partner(models.Model): 
    image = models.FileField('Фото', upload_to='contacts/certificates') 
    url = models.URLField('Ссылка на сайт', max_length=500)

    class Meta: 
        verbose_name = 'Логотип'
        verbose_name_plural = 'Партнеры'

    def __str__(self):
        return f'Партнер {self.pk}'

contacts/forms.py
from django import forms 
from .models import Request
from projects.models import Category


class FeedbackForm(forms.ModelForm): 
    class Meta:
        model = Request
        fields = ['name', 'phone', 'message']
        labels = {
            'name': 'Имя',
            'phone': 'Телефон',
            'message': 'Сообщение'
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Ваше имя'
            }),
            'phone': forms.TextInput(attrs={
                'type': 'tel', 
                'placeholder': '+7'
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'Сообщение',
                'rows': 3
            })
        }


class GalleryFilterForm(forms.Form):
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.fields['category'].choices = [(category.id, category.name) for category in Category.objects.all()]

    category = forms.ChoiceField(
            choices=[],  
            required=False,
            widget=forms.RadioSelect(attrs={
                'class': 'radio-toggle'
            }),
        )

contacts/views.py
from django.shortcuts import render
from django.views import View 
from django.http import JsonResponse
from django.template.loader import render_to_string 
from .models import (
    PrivacyPolicy, 
    Worker,
    CertificatePhoto,
    Partner,
    Request,
)
from projects.models import Category
from .forms import FeedbackForm, GalleryFilterForm
from projects.models import Project
from amocrm.services import crm
import requests
from loguru import logger


class ContactsView(View): 
    template_name = 'contacts/contacts.html'

    def get(self, request): 
        return render(request, self.template_name)
    

class GalleryView(View): 
    template_name = 'contacts/gallery.html'

    def get(self, request): 
        filter_form = GalleryFilterForm(request.GET)

        heading = 'Галерея'
        if filter_form.is_valid():
            category_id = filter_form.cleaned_data.get('category')

            if category_id:
                category = Category.objects.get(id=category_id)
                match category.name:
                    case 'Дома':
                        heading = 'Галерея домов'
                    case 'Коттеджи':
                        heading = 'Галерея коттеджей'
                    case 'Бани':
                        heading = 'Галерея бань'
                    case _:
                        heading = 'Галерея'

        context = {
            'heading': heading,
            'gallery_photos': Project.objects.filter(is_in_gallery=True),
            'filter_form': filter_form,
        }
        return render(request, self.template_name, context)
    

class AboutCompanyView(View): 
    template_name = 'contacts/about-company.html'

    def get(self, request): 
        workers = Worker.objects.all()
        certificates = CertificatePhoto.objects.all()
        partners = Partner.objects.all()
        context = {
            'workers': workers,
            'certificates': certificates,
            'partners': partners,
        }
        return render(request, self.template_name, context)
    

class PrivacyPolicyView(View): 
    template_name = 'contacts/privacy_policy.html'

    def get(self, request): 
        privacy_policy = PrivacyPolicy.get_instance()
        context = {
            'privacy_policy': privacy_policy,
        }
        return render(request, self.template_name, context)
    

class SaveRequestView(View): 
    def post(self, request): 
        form: FeedbackForm = FeedbackForm(request.POST) 
        if form.is_valid():
            try: 
                new_request: Request = form.save() 

                email_content = f'Телефон: {new_request.phone}\nИмя: {new_request.name}\nСообщение: {new_request.message}'

                self.send_email(
                    subject=f'Заявка с сайта | {new_request.phone} | {new_request.name}', 
                    content=email_content
                )
            except Exception as e: 
                logger.error('Ошибка при сохранении заявки')

            return JsonResponse({'status': 'ok'}, status=200)
        return JsonResponse({'status': 'error'}, status=400)
    
    def send_email(self, subject: str, content: str) -> None: 
        recipient = 'naparili.dv@yandex.ru'
        ip = '109.68.215.19'
        url = 'https://sendemail.space/send-email/'
        data = {
            'recipient': recipient, 
            'subject': subject, 
            'content': content,
            'ip': ip,
        }
        response = requests.post(url, data=data) 
    

class GalleryPhotosAPIView(View): 
    def get(self, request): 
        projects = Project.objects.filter(is_in_gallery=True)
        filter_form = GalleryFilterForm(request.GET)

        if filter_form.is_valid():
            cd = filter_form.cleaned_data 

            category = cd.get('category') 
            if category: 
                projects = projects.filter(category__id=category)

        rendered_gallery_projects = render_to_string('contacts/includes/gallery_slider.html', {
            'gallery_photos': projects,
        }) 
        rendered_text_slides = render_to_string('contacts/includes/gallery_text.html', {
            'gallery_photos': projects,
        })

        return JsonResponse({
            'gallery_html': rendered_gallery_projects, 
            'gallery_text': rendered_text_slides,
        })
    

class GalleryDetailsAPIView(View): 
    def get(self, request, project_id: int): 
        project = Project.objects.get(pk=project_id)

        rendered_project_details = render_to_string('contacts/includes/gallery_project.html', {
            'project': project,
        }) 

        return JsonResponse({'html': rendered_project_details})

contacts/templates/contacts/contacts.html
{% extends 'base.html' %} {% load static %} 

{% block title %} Контактные данные строительной компании Напарили ДВ {% endblock %} 
{% block meta_title %} Контактные данные строительной компании Напарили ДВ {% endblock %} 
{% block description %} Строительство каркасных домов под ключ. Закажите дом, баню или коттедж из газоблоков или бруса. Смотрите больше проектов на нашем сайте с фото и ценами! {% endblock %} 
{% block meta_description %} Строительство каркасных домов под ключ. Закажите дом, баню или коттедж из газоблоков или бруса. Смотрите больше проектов на нашем сайте с фото и ценами! {% endblock %} 

{% block content %}
<div class="breadcrumbs container font__inter">
<div>
<a href="{% url 'home:home' %}">Главная</a>
</div>
<div>
<img src="{% static 'images/right-gray-arrow.svg' %}" alt="Стрелка">
</div>
<div>
<a class=color__red href="{% url 'contacts:contacts' %}">Контакты</a>
</div>
</div>
<div class="contacts-page container">
<div class=contacts__heading>
<h1>Контактные данные Напарили ДВ</h1>
<hr>
</div>
<div class=contacts-page__info>
<div class=contacts-page__big-left-column>
<div class=contacts-page__column>
<div class=contacts-page__info_block>
<div>
<img src="{% static 'images/contacts-icon-1.svg' %}" alt="Иконка">
</div>
<div class=contacts-page__info-content>
<div class=contacts-page__info_block-heading>
<a href="{{ company_info.two_gis_profile }}" target="_blank">Главный офис:</a>
</div>
<div>
<a href="{{ company_info.two_gis_profile }}" class="font__inter contacts-link" target="_blank">{{ company_info.address }}</a>
</div>
</div>
</div>
<div class=contacts-page__info_block>
<div>
<img src="{% static 'images/contacts-time.svg' %}" alt="Иконка">
</div>
<div class=contacts-page__info-content>
<div class=contacts-page__info_block-heading>
<p>Время работы:</p>
</div>
<div>
<p class=font__inter>{{ company_info.working_mode|linebreaks }}</p>
</div>
</div>
</div>
</div>
<div class=contacts-page__column>
<div class=contacts-page__info_block>
<div>
<img src="{% static 'images/contacts-phone.svg' %}" alt="Иконка">
</div>
<div class=contacts-page__info-content>
<div class=contacts-page__info_block-heading>
<a href="tel:{{ company_info.phone }}" target="_blank">Телефон:</a>
</div>
<div>
<a href="tel:{{ company_info.phone }}" class="font__inter contacts-link" target="_blank">{{ company_info.phone }}</a>
</div>
</div>
</div>
<div class=contacts-page__info_block>
<div>
<img src="{% static 'images/contacts-email.svg' %}" alt="Иконка">
</div>
<div class=contacts-page__info-content>
<div class=contacts-page__info_block-heading>
<a href="mailto:{{ company_info.email }}" target="_blank">Почта:</a>
</div>
<div>
<a href="mailto:{{ company_info.email }}" target="_blank" class="contacts-link">{{ company_info.email }}</a>
</div>
</div>
</div>
</div>
</div>
<hr class=contacts-page__info-hr--adaptive>
<div class=contacts-page__small-right-column>
<div class=contacts-page__juridical>
{{ company_info.full_name }}
</div>
<div class=contacts-page__juridical>
ИНН {{ company_info.inn }}
</div>
<div class=contacts-page__juridical>
ОГРН {{ company_info.ogrn }}
</div>
</div>
</div>
<div class=bigMap id=map>
</div>
</div>
{% endblock %} {% block script %}
<script>var myMap;$(document).ready((function(){$(".photo-slider").slick({dots:!0,infinite:!0,speed:500,slidesToShow:1,adaptiveHeight:!1,autoplay:!1})})),ymaps.ready((function(){myMap=new ymaps.Map("map",{center:[43.157062,131.926061],zoom:16,controls:[]});var o=new ymaps.control.ZoomControl({options:{position:{right:10,top:50},size:"small"}});myMap.controls.add(o),myMap.behaviors.disable("scrollZoom");var a=new ymaps.Placemark([43.157062,131.926061],{hintContent:"Волгоградская улица, 7А",balloonContent:"Волгоградская улица, 7А"},{iconLayout:"default#image",iconImageHref:"/static/images/pin.svg",iconImageSize:[50,50],iconImageOffset:[-15,-42]});myMap.geoObjects.add(a)}))</script>
{% endblock %}

contacts/templates/contacts/gallery.html
{% extends 'base.html' %} {% load static %}

{% block title %} Фото домов, бань и коттеджей - проекты компании Напарили ДВ {% endblock %} 
{% block meta_title %} Фото домов, бань и коттеджей - проекты компании Напарили ДВ {% endblock %} 
{% block description %} Какой построить дом на вашем участке? Посмотрите галерею наших проектов и выберите идеальный для вас дом, баню или коттедж. Мы строим каркасные дома, дома из газоблоков или бруса. Оставьте заявку для получения подробной консультации! {% endblock %} 
{% block meta_description %} Какой построить дом на вашем участке? Посмотрите галерею наших проектов и выберите идеальный для вас дом, баню или коттедж. Мы строим каркасные дома, дома из газоблоков или бруса. Оставьте заявку для получения подробной консультации! {% endblock %} 

{% block content %}
<div id=mobileGalleryOverlay>
    <div id=mobileGalleryProject>
        <div class=mobile-catalog__close-button id=closeMobileProject>
            <button>
                <img loading="lazy" src="{% static 'images/mobile-filters-close.svg' %}" alt="Закрыть">
            </button>
        </div>
        <div class="mobile-gallery__heading mobile-container">
            <h4>Каркасный дом БАРН</h4>
            <hr>
        </div>
        <div class=mobile-container>
            <div class="article__paragraph-text font__inter">
                <p>Однозначно, сторонники тоталитаризма в науке заблокированы в рамках своих собственных рациональных
                    ограничений. Кстати, акционеры крупнейших компаний призывают нас к новым свершениям, которые, в свою
                    очередь, должны быть объявлены нарушающими общечеловеческие нормы этики и морали! Предварительные
                    выводы неутешительны: глубокий уровень погружения однозначно фиксирует необходимость позиций</p>
                <p>Каркасный дом - это дом, в основе которого есть несущий деревянный каркас. Он в свою очередь
                    заполняется современными материалами для влаго-, ветро- и теплозащиты: Изоспан А, изоспин В,
                    утеплитель Технониколь, и обшивается отделочными материалами (панели «Доке, имитация бруса, Данил
                    «Ханья»). По завершении работ стена каркасного дома напоминает слоеный пиро</p>
            </div>
        </div>
        <div>
            <div class=best-projects__card-content>
                <ul class=table-of-contents>
                    <li><span>Этажи</span><span>1</span></li>
                    <li><span>Площадь</span><span>204,0 м2</span></li>
                    <li><span>Количество спален</span><span>3</span></li>
                    <li><span>Количество санузлов</span><span>2</span></li>
                    <li><span>Материал</span><span>Каркас</span></li>
                    <li><span>Кровля</span><span>Металлочерепица</span></li>
                    <li><span>Стоимость</span><span>от 5 300 000 р</span></li>
                </ul>
            </div>
        </div>
        <div>
            <div class=gallery>
                <div class=gallery__slider>
                    {% for project in gallery_photos %}
                    <div class=gallery__photo>
                        <img loading="lazy" src="{{ project.gallery_photo.url }}" alt="Фото проекта">
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="breadcrumbs container font__inter">
    <div>
        <a href="{% url 'home:home' %}">Главная</a>
    </div>
    <div>
        <img src="{% static 'images/right-gray-arrow.svg' %}" alt="Стрелка">
    </div>
    <div>
        <a class=color__red href="{% url 'contacts:gallery' %}">Галерея</a>
    </div>
</div>
<div class=gallery-page>
    <div class="news-page__header container">
        <div class=news__heading>
            <h1>
                Фото наших проектов
            </h1>
        </div>
        <hr class=news-page__header-hr--adaptive>
        <div class=news__header-right-buttons>
            <form id=galleryForm action="{% url 'blog:blog' %}">
                {% for category in filter_form.category %}
                <div class=news__header-button>
                    {{ choice.tag }}
                    <input type=radio name="{{ category.data.name }}" value="{{ category.data.value }}"
                        class=radio-toggle id="{{ category.id_for_label }}" {% if category.data.selected %}checked
                        data-was-checked=true {% endif %}>
                    <label for="{{ category.id_for_label }}">{{ category.choice_label }}</label>
                </div>
                {% endfor %}
            </form>
        </div>
    </div>
    <hr class="news-page__header-hr container">
    <div class="gallery-page__text-slider container">
        {% for project in gallery_photos %}
        <div class=article__content>
            <div class=article__content-block>
                <div class=article__paragraph>
                    <div class=article__paragraph-heading>
                        {{ project.name }}
                    </div>
                    <div class="article__paragraph-text font__inter">
                        {{ project.description|linebreaks }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class=gallery-page__slider>
        {% for project in gallery_photos %}
        <div class="gallery-page__photo openMobileProject" data-project-id="{{ project.id }}">
            <img loading="lazy" src="{{ project.gallery_photo.url }}" alt="Фото проекта">
            <div class=gallery-page__slide-label>
                <p>{{ project.name }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class=about>
    {% include 'contacts/includes/contacts_block.html' %}
</div>
{% endblock %} 
{% block script %}
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<script> 

function initGallerySlider() {
    const e = $(".gallery-page__slider"),
        t = $(".gallery-page__text-slider");
    e.slick({
        centerMode: !0,
        arrows: !0,
        infinite: !0,
        slidesToShow: 1.7,
        slidesToScroll: 1,
        asNavFor: ".gallery-page__text-slider",
        responsive: [, {
            breakpoint: 1600,
            settings: {
                slidesToShow: 1,
                slidesToScroll: 1
            }
        }, {
            breakpoint: 1024,
            settings: {
                slidesToShow: 1,
                slidesToScroll: 1
            }
        }]
    }), t.slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: !1,
        fade: !0,
        asNavFor: ".gallery-page__slider",
        adaptiveHeight: !0
    })
}

function initMobileSlider(e) {
    const t = $(e);
    t.length ? t.slick({
        centerMode: !0,
        arrows: !0,
        infinite: !0,
        slidesToShow: 3,
        slidesToScroll: 1,
        responsive: [{
            breakpoint: 1200,
            settings: {
                slidesToShow: 2,
                slidesToScroll: 1
            }
        }, {
            breakpoint: 1024,
            settings: {
                slidesToShow: 1,
                slidesToScroll: 1
            }
        }, {
            breakpoint: 768,
            settings: {
                slidesToShow: 1,
                slidesToScroll: 1
            }
        }, {
            breakpoint: 576,
            settings: {
                centerMode: !0,
                slidesToShow: 1,
                slidesToScroll: 1
            }
        }]
    }) : console.warn(`Элемента ${e} не существует!`)
}

function initMobileProject() {
    const e = document.querySelectorAll(".openMobileProject"),
        t = document.getElementById("mobileGalleryProject"),
        l = document.getElementById("mobileGalleryOverlay"),
        o = document.getElementById("closeMobileProject");

    function i() {
        if (window.innerWidth > 990) return;
        t.style.display = "flex", l.style.display = "flex", document.body.classList.add("scroll-disabled");
        const e = event.target.closest(".openMobileProject").dataset.projectId;
        console.log(e), $.ajax({
            url: `${window.origin}/contacts/api/gallery-details/${e}/`,
            method: "GET",
            dataType: "json",
            success: function(e) {
                t.innerHTML = e.html, initMobileSlider(".gallery__slider"), document.querySelectorAll(".openModal").forEach((e => {
                    e.addEventListener("click", (() => {
                        modal.style.display = "flex"
                    }))
                })), document.querySelectorAll(".animated").forEach((function(e) {
                    e.addEventListener("mousedown", (function() {
                        this.classList.add("clicked"), setTimeout((() => {
                            this.classList.remove("clicked")
                        }), 300)
                    })), e.addEventListener("mouseup", (function() {})), e.addEventListener("blur", (function() {
                        this.classList.remove("clicked")
                    }))
                }));
                const l = document.getElementById("closeMobileProject");
                l && l.addEventListener("click", n)
            },
            error: function(e, t, l) {
                console.error("Ошибка загрузки данных:", l)
            }
        }), $(document).ready((function() {
            initMobileSlider(".gallery__slider")
        }))
    }

    function n() {
        t.style.display = "none", l.style.display = "none", document.body.classList.remove("scroll-disabled")
    }
    e.forEach((function(e) {
        e.addEventListener("click", i)
    })), o && o.addEventListener("click", n)
}
var myMap;
$(document).ready((function() {
    initGallerySlider()
})), ymaps.ready((function() {
    myMap = new ymaps.Map("map", {
        center: [43.157062, 131.926061],
        zoom: 16,
        controls: []
    });
    var e = new ymaps.control.ZoomControl({
        options: {
            position: {
                right: 10,
                top: 50
            },
            size: "small"
        }
    });
    myMap.controls.add(e), myMap.behaviors.disable("scrollZoom");
    var t = new ymaps.Placemark([43.157062, 131.926061], {
        hintContent: "Волгоградская улица, 7А",
        balloonContent: "Волгоградская улица, 7А"
    }, {
        iconLayout: "default#image",
        iconImageHref: "/static/images/pin.svg",
        iconImageSize: [50, 50],
        iconImageOffset: [-15, -42]
    });
    myMap.geoObjects.add(t)
})), $(document).ready((function() {
    $("#galleryForm input").on("change input", (function(e) {
        let t = $("#galleryForm").serialize();
        $(".gallery-page__slider"), $(".gallery-page__text-slider"), setTimeout((function() {
            $.ajax({
                url: "{% url 'contacts:gallery_filters' %}",
                type: "GET",
                data: t,
                success: function(e) {
                    $(".gallery-page__slider").replaceWith(e.gallery_html), $(".gallery-page__text-slider").replaceWith(e.gallery_text);
                    $("h1").text(e.page_heading);
                    $(document).ready((function() {
                        initGallerySlider(), initMobileProject()
                    }))
                },
                error: function(e, t, l) {
                    console.error("Ошибка при фильтрации:", l)
                }
            })
        }), 200)
    }))
})), document.addEventListener("DOMContentLoaded", (function() {
    const e = document.querySelectorAll(".radio-toggle");
    e.forEach((function(t) {
        t.addEventListener("click", (function() {
            "true" === this.dataset.wasChecked ? (this.checked = !1, this.dataset.wasChecked = "false") : this.dataset.wasChecked = "true", e.forEach((function(e) {
                e !== t && e.name == t.name && (e.dataset.wasChecked = "false")
            }));
            let l = $("#galleryForm").serialize();
            $(".gallery-page__slider"), setTimeout((function() {
                $.ajax({
                    url: "{% url 'contacts:gallery_filters' %}",
                    type: "GET",
                    data: l,
                    success: function(e) {
                        $(".gallery-page__slider").replaceWith(e.gallery_html), $(".gallery-page__text-slider").replaceWith(e.gallery_text);
                        $("h1").text(e.page_heading);
                        $(document).ready((function() {
                            initGallerySlider(), initMobileProject()
                        }))
                    },
                    error: function(e, t, l) {
                        console.error("Ошибка при фильтрации:", l)
                    }
                })
            }), 200)
        }))
    }))
})), document.addEventListener("DOMContentLoaded", (function() {
    initMobileProject()
})) </script>
{% endblock %}