NapariliDB/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

NapariliDV/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from .sitemaps import (
    HomeViewSitemap,
    StaticViewSitemap, 
    OtherStatisViewSitemap,
    ProjectViewSitemap, 
    BlogViewSitemap,
)

from home.views import handler404


sitemaps = {
    'home': HomeViewSitemap,
    'static': StaticViewSitemap,
    'other_static': OtherStatisViewSitemap,
    'projects': ProjectViewSitemap,
    'blog': BlogViewSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls', namespace='home')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contacts/', include('contacts.urls', namespace='contacts')),

    path('not-found/', handler404, name='not-found'),

    re_path(r'^robots\.txt$', serve, {
        'document_root': settings.BASE_DIR,
        'path': 'robots.txt',
    }),
    
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
)
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.handler404'

blog/urls.py
from django.urls import path
from .views import *


app_name = 'blog'


urlpatterns = [
    path('', BlogView.as_view(), name='blog'), 
    path('article/<slug:article_slug>', ArticleView.as_view(), name='article'), 
]

home/urls.py
from django.urls import path
from .views import *


app_name = 'home'


urlpatterns = [
    path('', HomeView.as_view(), name='home'), 

    path('api/best-projects-filter/', BestProjectsFilterAPIView.as_view(), name='best_projects_filter'),
]

projects/urls.py
from django.urls import path
from .views import *


app_name = 'projects'


urlpatterns = [
    path('catalog', CatalogView.as_view(), name='catalog'), 
    path('<slug:project_slug>/', ProjectView.as_view(), name='project'),
]

projects/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse
from home.services import convert_image_to_webp


class Category(models.Model): 
    name = models.CharField('Название', max_length=100)
    description = models.TextField('Описание')

    class Meta: 
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str: 
        return f'{self.name}'


class Material(models.Model): 
    name = models.CharField('Название', max_length=100)

    class Meta: 
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

    def __str__(self) -> str: 
        return f'{self.name}'


class RoofType(models.Model): 
    name = models.CharField('Название', max_length=100)

    class Meta: 
        verbose_name = 'Тип кровли'
        verbose_name_plural = 'Типы кровли'

    def __str__(self) -> str: 
        return f'{self.name}'


class Project(models.Model): 
    name = models.CharField('Название', max_length=100)
    description = models.TextField('Описание')
    square = models.FloatField('Площадь', validators=[MinValueValidator(0.0)])
    price = models.DecimalField('Цена', decimal_places=2, max_digits=12, null=True, blank=True)
    bedrooms_quantity = models.SmallIntegerField('Количество спален', default=1)
    floors_quantity = models.SmallIntegerField('Количество этажей', default=1)
    bathrooms_quantity = models.SmallIntegerField('Количество санузлов', default=1)
    estimates = models.FileField('Смета', upload_to='projects/estimates', null=True, blank=True)
    is_the_best = models.BooleanField('Входит в топ', default=False)
    is_in_gallery = models.BooleanField('Отображается в галерее', default=False)
    gallery_photo = models.ImageField('Фото в галерее', upload_to='gallery', blank=True, null=True)
    slug = models.SlugField(verbose_name='Слаг', max_length=500)
    category = models.ForeignKey(
        verbose_name='Категория', 
        to=Category, 
        on_delete=models.CASCADE, 
        related_name='category_projects'
    )
    material = models.ForeignKey(
        verbose_name='Материал', 
        to=Material, 
        on_delete=models.CASCADE, 
        related_name='material_projects', 
        null=True, 
        blank=True,
    )
    roof_type = models.ForeignKey(
        verbose_name='Тип кровли', 
        to=RoofType, 
        on_delete=models.CASCADE, 
        related_name='roof_type_projects', 
        null=True, 
        blank=True,
    )

    class Meta: 
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def save(self, *args, **kwargs):
        if self.pk:
            old_image = self.__class__.objects.filter(pk=self.pk).first().gallery_photo
            if old_image and self.gallery_photo and old_image.name == self.gallery_photo.name:
                super(self.__class__, self).save(*args, **kwargs)
                return
            
        webp_image = convert_image_to_webp(self.gallery_photo)
        if webp_image:
            self.gallery_photo.save(webp_image.name, webp_image, save=False)
        
        super(self.__class__, self).save(*args, **kwargs)

    def __str__(self) -> str: 
        return f'{self.name} | {self.price} р'
    
    def get_absolute_url(self): 
        return reverse('projects:project', args=[self.slug])
    

class Layout(models.Model): 
    name = models.CharField('Название', max_length=50)
    image = models.ImageField('Изображение', upload_to='laoyouts') 
    area = models.FloatField('Площадь')
    size = models.CharField('Габариты', max_length=120)
    ceiling_height = models.CharField('Высота потолков', max_length=120)
    seasonality = models.CharField('Сезонность', max_length=120)
    project = models.ForeignKey(verbose_name='Проект', to=Project, on_delete=models.CASCADE, related_name='layouts')

    class Meta: 
        verbose_name = 'Планировка'
        verbose_name_plural = 'Планировки'

    def save(self, *args, **kwargs):
        if self.pk:
            old_image = self.__class__.objects.filter(pk=self.pk).first().image
            if old_image and self.image and old_image.name == self.image.name:
                super().save(*args, **kwargs)
                return

        webp_image = convert_image_to_webp(self.image)
        if webp_image:
            self.image.save(webp_image.name, webp_image, save=False)

        super().save(*args, **kwargs)  


class ProjectPhoto(models.Model): 
    image = models.ImageField('Изображение', upload_to='projects', null=True, blank=True)
    project = models.ForeignKey(verbose_name='Проект', to=Project, on_delete=models.CASCADE, related_name='photos', null=True)

    class Meta: 
        verbose_name = 'Фото проекта'
        verbose_name_plural = 'Фото проекта'

    def save(self, *args, **kwargs):
        if self.pk:
            old_image = self.__class__.objects.filter(pk=self.pk).first().image
            if old_image and self.image and old_image.name == self.image.name:
                super(self.__class__, self).save(*args, **kwargs)
                return

        webp_image = convert_image_to_webp(self.image)
        if webp_image:
            self.image.save(webp_image.name, webp_image, save=False)
        
        super(self.__class__, self).save(*args, **kwargs)

    def __str__(self) -> str: 
        return f'{self.image}'

projects/forms.py
from django import forms 
from django.db import models
from .models import (
    Project, 
    Category, 
    Material, 
    RoofType, 
)
from .templatetags.price_filters import price_format
from .services import (
    get_max_project_price, 
    get_min_project_price, 
    get_max_project_square, 
    get_min_project_square
)


class CatalogFiltersForm(forms.Form): 
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)

        self.max_project_square = int(get_max_project_square())
        self.min_project_square = int(get_min_project_square())
        self.fields['square_max'].widget.attrs['max'] = self.max_project_square
        self.fields['square_max'].widget.attrs['placeholder'] = f'{price_format(self.max_project_square)} м²'
        self.fields['square_min'].widget.attrs['max'] = self.max_project_square
        self.fields['square_min'].widget.attrs['placeholder'] = f'{price_format(self.min_project_square)} м²'

        self.max_product_price = round(get_max_project_price(), 0)
        self.fields['price_max'].widget.attrs['max'] = self.max_product_price
        self.fields['price_max'].widget.attrs['placeholder'] = f'{price_format(self.max_product_price)} ₽'

        self.min_product_price = round(get_min_project_price(), 0)
        self.fields['price_max'].widget.attrs['min'] = self.min_product_price
        self.fields['price_max'].widget.attrs['max'] = self.max_product_price
        self.fields['price_min'].widget.attrs['placeholder'] = f'{price_format(self.min_product_price)} ₽'

        self.fields['price_min'].widget.attrs['max'] = self.max_product_price

        self.fields['categories'].choices = [(category.id, category.name) for category in Category.objects.all()]
        self.fields['materials'].choices = [(None, "Все")] + [(material.id, material.name) for material in Material.objects.all()]
        self.fields['roof_types'].choices = [(None, "Все")] + [(roof_type.id, roof_type.name) for roof_type in RoofType.objects.all()]


    categories = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        required=False
    )
    materials = forms.ChoiceField(
        widget=forms.Select(),
        required=False,
        label="Выберите материал",
        choices=[],
    )

    roof_types = forms.ChoiceField(
        widget=forms.Select(),
        required=False,
        label="Выберите тип кровли",
        choices=[],
    )
    price_min = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        label='Мин. цена',
        widget=forms.NumberInput(
            attrs={ 
                # 'step': 100000,
            }
        ), 
    )
    price_max = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        widget=forms.NumberInput(
            attrs={ 
                # 'step': 100000,
            }
        ), 
    )
    square_min = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        widget=forms.NumberInput(
            attrs={ 
                # 'step': 5,
            }
        ), 
    )
    square_max = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        widget=forms.NumberInput(
            attrs={ 
                # 'step': 5,
            }
        ), 
    )
    floors_quantity = forms.ChoiceField(
        choices=[(i, i) for i in range(1, 3)],  
        required=False,
        widget=forms.RadioSelect(attrs={
            'class': 'radio-toggle'
        }),
    )
    bedrooms_quantity = forms.ChoiceField(
        choices=[(i, i) for i in range(1, 5)],
        required=False,
        widget=forms.RadioSelect(attrs={
            'class': 'radio-toggle'
        }),
    )
    bathrooms_quantity = forms.ChoiceField(
        choices=[(i, i) for i in range(1, 4)], 
        required=False,
        widget=forms.RadioSelect(attrs={
            'class': 'radio-toggle'
        }),
    )

projects/views.py
from django.shortcuts import render
from django.views import View 
from django.db.models import F, Case, When, Value, FloatField
from .models import (
    Project,
    Category,
)
from .services import get_paginated_collection
import random
from .forms import CatalogFiltersForm


class CatalogView(View): 
    template_name = 'projects/catalog.html'

    def get(self, request): 
        projects = Project.objects.all() 
        form = CatalogFiltersForm(request.GET)

        heading = 'Каталог проектов с фото'

        if form.is_valid():
            cd = form.cleaned_data
            
            selected_categories = cd.get('categories')
            if selected_categories:
                projects = projects.filter(category__id__in=selected_categories)

            if len(selected_categories) == 1: 
                (category_id,) = selected_categories
                category_name = Category.objects.get(pk=category_id).name 
                match category_name: 
                    case 'Дома': 
                        heading = f'Каталог проектов домов с фото'
                    case 'Бани': 
                        heading = f'Каталог проектов бань с фото'
                    case 'Коттеджи': 
                        heading = f'Каталог проектов коттеджей с фото'


            selected_materials = cd.get('materials')
            if selected_materials:
                projects = projects.filter(material__id=selected_materials)

            selected_roof_types = cd.get('roof_types')
            if selected_roof_types:
                projects = projects.filter(roof_type__id=selected_roof_types)

            price_min = cd.get('price_min')
            if price_min is not None:
                projects = projects.filter(price__gte=price_min)

            price_max = cd.get('price_max')
            if price_max is not None:
                projects = projects.filter(price__lte=price_max)

            square_min = cd.get('square_min')
            if square_min is not None:
                projects = projects.filter(square__gte=square_min)

            square_max = cd.get('square_max')
            if square_max is not None:
                projects = projects.filter(square__lte=square_max)

            floors_quantity = cd.get('floors_quantity')
            if floors_quantity:
                projects = projects.filter(floors_quantity=floors_quantity)

            bedrooms_quantity = cd.get('bedrooms_quantity')
            if bedrooms_quantity:
                projects = projects.filter(bedrooms_quantity=bedrooms_quantity)

            bathrooms_quantity = cd.get('bathrooms_quantity')
            if bathrooms_quantity:
                projects = projects.filter(bathrooms_quantity=bathrooms_quantity)
            
        projects = get_paginated_collection(request, projects, 12)

        context = {
            'form': form,
            'projects': projects,
            'page_heading': heading,
        }

        return render(request, self.template_name, context)

    

class ProjectView(View): 
    template_name = 'projects/project.html'
    
    def get(self, request, project_slug: str): 
        project = Project.objects.get(slug=project_slug) 

        category_ids = list(Project.objects.filter(category=project.category).exclude(id=project.id).values_list('id', flat=True)) 
        material_ids = list(Project.objects.filter(category=project.category).exclude(id=project.id).values_list('id', flat=True)) 
        all_projects_ids = list(Project.objects.all().exclude(id=project.id).values_list('id', flat=True)) 

        ids = category_ids if len(category_ids) >= 3 else material_ids if len(material_ids) >= 3 else all_projects_ids
        ids_len = len(ids)

        similar_projects_ids = random.sample(ids, min(6, ids_len))
        if id in similar_projects_ids:
            similar_projects_ids.remove(id) 
        similar_projects = Project.objects.filter(id__in=similar_projects_ids)

        context = {
            'project': project,
            'similar_projects': similar_projects,
        }
        return render(request, self.template_name, context)

projects/templates/projects/project.html
{% extends 'base.html' %} 
{% load static %} 
{% load price_filters %}
{% load markdown_filters %}

{% block title %} {{ project.name }} - проект с фото, ценами и схемой | Напарили ДВ {% endblock %}
{% block meta_title %} {{ project.name }} - проект с фото, ценами и схемой | Напарили ДВ {% endblock %}
{% block description %} Проект дома {{ project.name }} - это уникальный объект типа {{ project.category }}. Мы составим
уникальный проект дома для вашего участка и согласуем объемы и площадь. Оставьте заявку и мы свяжемся с вами в ближайшее
время! {% endblock %}
{% block meta_description %} Проект дома {{ project.name }} - это уникальный объект типа {{ project.category }}. Мы
составим уникальный проект дома для вашего участка и согласуем объемы и площадь. Оставьте заявку и мы свяжемся с вами в
ближайшее время! {% endblock %}

{% block content %}
<div class="breadcrumbs container font__inter">
    <div>
        <a href="{% url 'home:home' %}">Главная</a>
    </div>
    <div>
        <img src="{% static 'images/right-gray-arrow.svg' %}" alt="Стрелка">
    </div>
    <div>
        <a href="{% url 'projects:catalog' %}">Каталог</a>
    </div>
    <div>
        <img src="{% static 'images/right-gray-arrow.svg' %}" alt="Стрелка">
    </div>
    <div>
        <a class=color__red href="{{ project.get_absolute_url }}">{{ project.name }}</a>
    </div>
</div>
<div class="project container" id="projectContainer" data-project-name="{{ project.name }}">
    <div class=project__slider>
        <div class=project__current-slide href="">
            {% for photo in project.photos.all %}
            <div>
                <a href="{{ photo.image.url }}">
                    <img src="{{ photo.image.url }}" alt="Фото проекта">
                </a>
            </div>
            {% endfor %}
        </div>
        <div class=project__slider-nav>
            {% for photo in project.photos.all %}
            <div class=project__slide>
                <img src="{{ photo.image.url }}" alt="Фото проекта">
            </div>
            {% endfor %}
        </div>
    </div>
    <div class=project__details>
        <div class=project__buttons-group>
            {% if project.estimates %}
            <a href="{{ project.estimates.url }}" class=project__download-estimates>
                <button>Скачать смету</button>
            </a>
            {% endif %}
            <div class=project__discount>
                <button>Скидка 5%</button>
            </div>
        </div>
        <div class="project__heading container">
            <h1>{{ project.name }}</h1>
            <hr>
        </div>
        <div class="project__buttons-group--adaptive container">
            {% if project.estimates %}
            <a href="{{ project.estimates.url }}" class=project__download-estimates--adaptive>
                <button>Скачать смету</button>
            </a>
            {% endif %}
            <div class=project__discount--adaptive>
                <button>Скидка 5%</button>
            </div>
        </div>
        <div class=project__slider--adaptive>
            {% for photo in project.photos.all %}
            <div class=project__slide--adaptive>
                <a href="{{ photo.image.url }}">
                    <img loading="lazy" src="{{ photo.image.url }}" alt="Фото проекта">
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="project__parameters container">
            <ul class=table-of-contents>
                {% if project.floors_quantity > 0 %}
                    <li><span>Этажи</span><span>{{ project.floors_quantity }}</span></li>
                {% endif %}
                <li><span>Площадь</span><span>{{ project.square }} м²</span></li>
                {% if project.bedrooms_quantity > 0 %}
                    <li><span>Количество спален</span><span>{{ project.bedrooms_quantity }}</span></li>
                {% endif %}
                {% if project.bathrooms_quantity > 0 %}
                    <li><span>Количество санузлов</span><span>{{ project.bathrooms_quantity }}</span></li>
                {% endif %}
                {% if project.material %}
                    <li><span>Материал</span><span>{{ project.material }}</span></li>   
                {% endif %}
                {% if project.roof_type %}
                    <li><span>Кровля</span><span>{{ project.roof_type }}</span></li>
                {% endif %}
                {% if project.price %}
                    <li><span>Стоимость</span><span>от {{ project.price|price_format }} р</span></li>
                {% endif %}
            </ul>
        </div>
        <div class="project__order-button-area">
            <div class="project__credit container">
                <div>Дом подходит под ипотеку,<br> или кредит</div>
            </div>
            <div class="project__order-button animated openModal">
                <button class="orderButton" data-project-name="{{ project.name }}">
                    <img src="{% static 'images/order-button.svg' %}" alt="Заказать">
                </button>
            </div>
        </div>
    </div>
</div>
{% if project.layouts.all %}
<div class="info container" style="padding-bottom: 0px !important;">
    <div class=info__heading>
        <p>Доступные планировки</p>
        <hr>
    </div>
    <div class="layouts">
        {% for layout in project.layouts.all %}
            <div class="layout__card">
                <div>
                    <a href="{{ layout.image.url }}">
                        <img  src="{{ layout.image.url }}" alt="Фото планировки">
                    </a>
                </div>
                <div class="layout__card-content">
                    <div class="layout__card-heading font__involve-medium">
                        <p>{{ layout.name }}</p>
                    </div>
                    <div class="layout__card-text">
                        <p>Площадь {{ layout.area }} м2</p>
                        <p>Габариты {{ layout.size }}</p>
                        <p>Высота потолков {{ layout.ceiling_height }}</p>
                        <p>Сезонность {{ layout.seasonality }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="info container">
    <div class=info__heading>
        <p>{{ project.category.name }}</p>
        <hr>
    </div>
    <div class=info__row>
        <div class="info__paragraph font__inter">
            {{ project.category.description|markdown }}
        </div>
    </div>
</div>
<div class="similar-projects container">
    <div>
        <h4 class=similar-projects__heading>Похожие проекты</h4>
    </div>
    <div class=similar-projects__cards>
        {% for project in similar_projects %}
        <div class=similar-projects__slider-item>
            <div class=photo-slider>
                {% for photo in project.photos.all %}
                    {% if forloop.counter <= 2 or forloop.revcounter <= 2 %}
                        <div class="similar-projects__card-image photo-slider-item">
                            <a href="{{ project.get_absolute_url }}">
                                <img loading="lazy" src="{{ photo.image.url }}" alt="Фото проекта">
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
            <div class=similar-projects__card-text-container>
                <div class=similar-projects__card-heading>
                    <a href="{{ project.get_absolute_url }}">{{ project.name }}</a>
                </div>
                <hr>
                <div class=similar-projects__card-content>
                    <ul class=table-of-contents>
                        <li><span>Площадь</span><span>{{ project.square }} м²</span></li>
                        {% if project.bedrooms_quantity > 0 %}
                            <li><span>Количество спален</span><span>{{ project.bedrooms_quantity }}</span></li>
                        {% endif %}
                        {% if project.bathrooms_quantity > 0 %}
                            <li><span>Количество санузлов</span><span>{{ project.bathrooms_quantity }}</span></li>
                        {% endif %}
                        {% if project.price %}
                            <li><span>Стоимость</span><span>от {{ project.price|price_format }} р</span></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="similar-projects__order-button openModal">
                <button class="orderButton" data-project-name="{{ project.name }}">Заказать строительство</button>
            </div>
            <div class=similar-projects__more-button>
                <a href="{{ project.get_absolute_url }}">Узнать подробнее</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% include 'contacts/includes/contacts_block.html' %} {% endblock %} {% block script %}
<link rel="preload" href="{% static 'css/luminous-lightbox.css' %}" as="style"
    onload="this.onload=null;this.rel='stylesheet'">
<script type=module src="{% static 'js/luminous-lightbox/luminous-lightbox.js' %}"></script>
<style class=lum-base-styles>
    .lum-img {
        max-height: 90vh !important;
        max-width: 1200px !important;
    }
    @media (max-width: 1200px) {
        .lum-img {
            max-width: 100% !important;
        }
    }
    @media (max-width: 990px) {
        .lum-gallery-button {
            display: none !important;
        }
    }
    @keyframes lum-noop {
        0% {
            zoom: 1
        }
    }

    .lum-lightbox {
        position: fixed;
        display: none;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0
    }

    .lum-lightbox.lum-open {
        display: block;
        z-index: 1000000
    }

    .lum-lightbox.lum-closing,
    .lum-lightbox.lum-opening {
        animation: lum-noop 1ms
    }

    .lum-lightbox-inner {
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        overflow: hidden
    }

    .lum-lightbox-loader {
        display: none
    }

    .lum-lightbox-inner img {
        max-width: 100%;
        max-height: 100%
    }

    .lum-lightbox-image-wrapper {
        vertical-align: middle;
        display: table-cell;
        text-align: center;
        background-color: rgba(0, 0, 0, .5)
    }

    .lum-img {
        object-fit: cover !important;
        width: 85vw
    }

    @media (max-width:990px) {
        .lum-img {
            width: 100vw
        }
    }
</style>
<script
    type=module>import{L as LuminousGallery}from"/static/js/luminous-lightbox/luminous-lightbox.js";

    function initGallery() {
        var l = document.querySelectorAll(".project__current-slide a");
        const e = {
            showCloseButton: !0
        };
        l.length > 0 && new LuminousGallery(l, e);
        var o = document.querySelectorAll(".project__slide--adaptive a");
        console.log(o), l.length > 0 && new LuminousGallery(o)

        var layouts = document.querySelectorAll(".layout__card a");
        l.length > 0 && new LuminousGallery(layouts)
    }
    
    initGallery()
</script>
<script>var myMap; $(".project__current-slide").slick({ slidesToShow: 1, slidesToScroll: 1, arrows: !0, fade: !0, asNavFor: ".project__slider-nav" }), $(".project__slider-nav").slick({ slidesToShow: 3, slidesToScroll: 1, asNavFor: ".project__current-slide", dots: !1, arrows: !1, focusOnSelect: !0 }), $(".project__slider--adaptive").slick({ centerMode: !0, slidesToShow: 1, slidesToScroll: 1, dots: !1, arrows: !1, focusOnSelect: !0, responsive: [{ breakpoint: 1200, settings: { slidesToShow: 2, slidesToScroll: 1 } }, { breakpoint: 820, settings: { slidesToShow: 1, slidesToScroll: 1 } }, { breakpoint: 576, settings: { slidesToShow: 1, slidesToScroll: 1 } }] }), 

$(document).ready((function () { $(".similar-projects__cards").slick({ arrows: !0, infinite: !0, slidesToShow: 3, slidesToScroll: 1, 
    // focusOnSelect: true, 
    responsive: [{ breakpoint: 1024, settings: { slidesToShow: 2, slidesToScroll: 1 } }, { breakpoint: 768, settings: { centerMode: !0, slidesToShow: 1, slidesToScroll: 1 } }, { breakpoint: 576, settings: { centerMode: !0, slidesToShow: 1, slidesToScroll: 1 } }, { breakpoint: 410, settings: { centerMode: !1, slidesToShow: 1, slidesToScroll: 1 } }] }), 
    $(".photo-slider").slick({ dots: !0, infinite: !0, speed: 500, slidesToShow: 1, adaptiveHeight: !1, autoplay: !1, arrows: !1 }), $(".photo-slider").on("touchstart mousedown", (function (o) { o.stopPropagation() })) })), ymaps.ready((function () { myMap = new ymaps.Map("map", { center: [43.157062, 131.926061], zoom: 16, controls: [] }); var o = new ymaps.control.ZoomControl({ options: { position: { right: 10, top: 50 }, size: "small" } }); myMap.controls.add(o), myMap.behaviors.disable("scrollZoom"); var s = new ymaps.Placemark([43.157062, 131.926061], { hintContent: "Волгоградская улица, 7А", balloonContent: "Волгоградская улица, 7А" }, { iconLayout: "default#image", iconImageHref: "/static/images/pin.svg", iconImageSize: [30, 42], iconImageOffset: [-15, -42] }); myMap.geoObjects.add(s) }))

    function initPrescriptionMessageInModal() {
        const orderButtons = document.querySelectorAll(".orderButton"); 
        console.log(orderButtons)
        const messageField = document.getElementById("id_message"); 
        orderButtons.forEach((button) => {
            button.addEventListener("click", function () {
                console.log('Нажатие')
                const projectName = button.getAttribute("data-project-name");
                messageField.value = `Я заинтересовался проектом ${projectName}`;
        });

        }) 
    }
    document.addEventListener("DOMContentLoaded", function () {
        initPrescriptionMessageInModal();
    });
</script>
{% endblock %}